termos = int(input('Digite o tanto de termos que você quer ver da sequência de fibonacci: '))
t1 = 0
t2 = 1
print(f'{t1} {t2} ', end='')
while termos >=3:
    t3 = t1 + t2
    print(f'{t3}', end=' ')
    t1 = t2
    t2 = t3
    termos -= 1